#!/bin/bash
set -e

if [[ -z "$VERSION" ]]; then
    VERSION=$(git rev-parse HEAD)
fi

if [[ -z "$DATE" ]]; then
    DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
fi

VERSION_PACKAGE='github.com/ldez/prm/meta'
GO_BUILD_CMD="go build -ldflags"
GO_BUILD_OPT="-s -w -X ${VERSION_PACKAGE}.Version=${VERSION} -X ${VERSION_PACKAGE}.BuildDate=${DATE}"

# Build binaries
OS_PLATFORM_ARG=(linux windows darwin)
OS_ARCH_ARG=(amd64)
for OS in ${OS_PLATFORM_ARG[@]}; do
  BIN_EXT=''
  if [[ "$OS" == "windows" ]]; then
    BIN_EXT='.exe'
  fi
  for ARCH in ${OS_ARCH_ARG[@]}; do
    echo "Building binary for ${OS}/${ARCH}..."
    GOARCH=${ARCH} GOOS=${OS} CGO_ENABLED=0 ${GO_BUILD_CMD} "${GO_BUILD_OPT}" -o "dist/prm_${OS}-${ARCH}${BIN_EXT}"
  done
done
