run:
  timeout: 2m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    enable-all: true
#    disable:
#      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/pkg/errors
  godox:
    keywords:
      - FIXME
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100
  forbidigo:
    forbid:
      # - ^panic$
      - ^print(ln)?$
      # - ^fmt\.Print(ln|f)?$
      - ^spew\.Print(f|ln)?$
      - ^spew\.Dump$
      - ^spew\.(F|S)dump(f|ln)?$

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - maligned # deprecated
    - lll
    - dupl
    - prealloc
    - scopelint
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - testpackage
    - paralleltest
    - tparallel
    - nestif
    - exhaustive
    - exhaustivestruct
    - cyclop

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'G101'
    - 'G301'
    - 'G306' # Expect WriteFile permissions to be 0600 or less
  exclude-rules:
    - path: meta/version.go
      text: '(version|date|commit) is a global variable'
    - path: config/config.go
      text: 'getPathFunc is a global variable'
    - path: (.+)_test.go
      linters:
        - funlen
    - path: (.+)_test.go
      text: 'fieldalignment: '
