version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - lll
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^spew\.Print(f|ln)?$
        - pattern: ^spew\.Dump$
        - pattern: ^spew\.(F|S)dump(f|ln)?$
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - unnamedResult
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - paramTypeCombine # already handle by gofumpt.extra-rules
        - whyNoLint # already handle by nolintlint
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        hugeParam:
          sizeThreshold: 100
    gocyclo:
      min-complexity: 12
    godox:
      keywords:
        - FIXME
    gosec:
      excludes:
        - 'G101' # Potential hardcoded credentials
        - 'G301' # Expect directory permissions to be 0750 or less
        - 'G304' # Potential file inclusion via variable
        - 'G307' # Deferring unsafe method "Close" on type "*os.File"
        - 'G306' # Expect WriteFile permissions to be 0600 or less
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    tagliatelle:
      case:
        rules:
          json: snake

  exclusions:
    warn-unused: true
    presets:
      - comments
    rules:
      - path: meta/version.go
        text: (version|date|commit) is a global variable
      - path: config/config.go
        text: getPathFunc is a global variable
      - linters:
          - funlen
        path: (.+)_test.go


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
