project_name: prm

builds:
  - binary: prm
    ldflags:
      - -s -w -X github.com/ldez/prm/v3/meta.version={{.Version}} -X github.com/ldez/prm/v3/meta.commit={{.Commit}} -X github.com/ldez/prm/v3/meta.date={{.Date}}

    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: prm
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

brews:
  - github:
      owner: ldez
      name: homebrew-tap
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
    folder: Formula
    homepage: https://github.com/ldez/prm
    description: Pull Request Manager for Maintainers
    test: |
      system "#{bin}/prm version"

scoop:
  bucket:
    owner: ldez
    name: scoop-bucket
  commit_author:
    name: ldez
    email: ldez@users.noreply.github.com
  homepage: https://github.com/ldez/prm
  description: Pull Request Manager for Maintainers
  license: APACHE

#release:
#  disable: true