= PRM - Pull Request Manager

image:https://travis-ci.org/ldez/prm.svg?branch=master["Build Status", link="https://travis-ci.org/ldez/prm"]

If you are a maintainer of Open Source Software, you need to review a lot of PR, this tool is made for you.

Due to the GitHub feature (link:https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/["repository maintainer permissions on existing pull requests"]), now we can edit real PR branch.
This tool allow to easily manage PR branches and remotes.

Feature:

* Checkout a PR by his number.
* Remove (clean) a PR by his number.
* Remove (clean) all PR for a project.
* Push force a PR (auto).
* Manage all your repositories.
* Save your configuration: `~/.prm`
* Only works with GitHub.

Install:

[source, shell]
----
# TODO
----


== Checkout

[source, shell]
----
prm c -n 1234
# or
prm c --number=1234
----

* Add the user git remote named with the user login.
* Checkout the PR branch named like that: `<PR_NUMBER>--<BRANCH_NAME>`
+
ex: `1234\--myBranch`

== Remove

== By Number

[source, shell]
----
prm rm -n 1234
# or
prm rm --number=1234
----

* Remove the local branch.
* Remove the user git remote if necessary.

== All

[source, shell]
----
prm rm --all
----

* Remove all PR related local branches.
* Remove all PR related git remote.

== Push Force

[source, shell]
----
# recommended
prm pf

# Manual
prm pf -n 1234
# or
prm pf --number=1234
----

* Push force the PR related branch.
* Detect the PR number from the branch name.

== List

[source, shell]
----
# display local branches related to PR. (current project only)
prm list

# display local branches related to PR. (all projects)
prm list --all
----

* Display local branches related to PR for:
** current project
** all projects
